[package]
name = "faultforge-master"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
faultforge-proto = { path = "../proto" }
faultforge-fault = { path = "../fault", features = ["proto"] }
tonic = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
config = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
reqwest = { version = "0.13.4", default-features = false, features = ["json"] }
tempfile = { workspace = true }

[lints]
workspace = true
